
# mongo:6.0.4

version: '3.8'

services:
  cloud-backend-service:
    # platform: linux/amd64,linux/arm64
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.staging
    image: prasanti85/mernbackend:staging
    container_name: cloud-backend
    command: node src/backend.js
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongodb-service
    # env_file: ./backend/.env
    # environment:
      # - NODE_ENV=Development
    networks:
      - mernnet

  mongodb-service:
    image: mongo:6.0.4
    container_name: mongodb
    restart: always
    # command: mongod
    # environment:
      # # provide your credentials here
      # - MONGO_INITDB_ROOT_USERNAME=user
      # - MONGO_INITDB_ROOT_PASSWORD=password
      # - MONG_INITDB_DATABASE=devEventManagement
    volumes:
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - mernnet

  cloud-frontend-service:
    # platform: linux/amd64,linux/arm64
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile.staging
    image: prasanti85/mernfrontend
    container_name: cloud-frontend
    command: npm run build-stage
    # environment:
    #   - REACT_APP_BASE_URL=http://localhost:3000
    #   - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./frontend/:/usr/app
      - ./frontend/.env:/usr/app/.env
      - /usr/app/node_modules
    depends_on:
      - cloud-backend-service
    ports:
      - "3000:3000"
    networks:
      - mernnet

networks:
  mernnet:
    ipam:
      driver: default

volumes:
    # mysql_data:
    data-volume:
    node_modules:
    web-root: