
# mongo:6.0.4

version: '3.8'

services:
  mern-backend-service:
    # platform: linux/amd64,linux/arm64
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.staging
    image: prasanti85/mernbackend:dev
    container_name: mern-backend
    command: node src/server.js
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "7002:4000"
    depends_on:
      - mern-mongodb-service
    # env_file: ./backend/.env
    # environment:
      # - NODE_ENV=Development
    networks:
      - mernnet

  mern-mongodb-service:
    image: mongo:6.0.4
    container_name: mern-mongodb
    restart: always
    command: mongod
    # environment:
      # provide your credentials here
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      # - MONGO_INITDB_DATABASE=devEventManagement
      # - MONGODB_DATABASE=devEventManagement
      # - MONGODB_USER=user
      # - MONGODB_PASSWORD=root
    volumes:
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      # - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
      - data-volume:/data/db
    ports:
      - "27016:27017"
    networks:
      - mernnet

  mern-frontend-service:
    # platform: linux/amd64,linux/arm64
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile.staging
    image: prasanti85/mernfrontend:dev
    container_name: mern-frontend
    command: npm run start
    # environment:
    #   - REACT_APP_BASE_URL=http://localhost:3000
    #   - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - ./frontend/.env:/app/.env
      - /app/node_modules
    depends_on:
      - mern-backend-service
    ports:
      - "7001:3000"
    networks:
      - mernnet

networks:
  mernnet:
    ipam:
      driver: default

volumes:
    # mysql_data:
    data-volume:
    node_modules:
    web-root: