
# mongo:6.0.4

version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: prasanti85/webmernserver:dev
    container_name: server
    command: npm run start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=Development
    networks:
      - mernnet

  mongo:
    image: mongo:6.0.4
    container_name: mongo
    restart: always
    # command: mongod
    # environment:
      # # provide your credentials here
      # - MONGO_INITDB_ROOT_USERNAME=user
      # - MONGO_INITDB_ROOT_PASSWORD=password
      # - MONG_INITDB_DATABASE=devEventManagement
    volumes:
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - mernnet

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: prasanti85/apimernserver:dev
    container_name: client
    command: npm start
    # environment:
    #   - REACT_APP_BASE_URL=http://localhost:3000
    #   - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./client/:/usr/app
      - ./client/.env:/usr/app/.env
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - mernnet

networks:
  mernnet:
    ipam:
      driver: default

volumes:
    # mysql_data:
    data-volume:
    node_modules:
    web-root: