apiVersion: v1
kind: Service
metadata:
  name: webeventservice
spec:
  selector:
    app: webevent
  ports:
    - port: 80
      protocol: TCP
      # targetPort: 4800
  type: LoadBalancer

  # type: ClusterIP
  # ports:
  #   - port: 4800
  #     targetPort: 4800

  # type: NodePort
  # ports:
  #   - port: 4800
  #     protocol: TCP
  #     targetPort: 4800
  #     nodePort: 30008

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webeventdeployment
  labels:
    app: webevent  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webevent
  template:
    metadata:
      labels:
        app: webevent
    spec:
      containers:
      - name: webeventcontainer
        image: prasanti85/webmerneventsserver:eks
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
status: {}

---

# aws eks --region us-west-1 update-kubeconfig --name eksClusterPPM

# kubectl create -f kubernetes/web-eks.yaml
# kubectl apply -f=kubernetes/web-eks.yaml
# kubectl get deployments && kubectl get pods && kubectl get namespaces && kubectl get services 

# kubectl delete -f=kubernetes/web-eks.yaml

